name: lint
on: [push, pull_request]
jobs:
  ci:
    name: Run black and pylint tools
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: false
          black: true
          flake8: false

      - name: Analysing the code with pylint
        run: |
          uv run pylint --output-format=text ./**/*.py
